theme = "bad-wolf"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 0
alert = 0

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
marquee_interval = 2
marquee_speed = 0.25

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
