(require 'package)

(add-to-list 'package-archives (cons "melpa" "https://melpa.org/packages/") t)
(add-to-list 'package-archives (cons "marmalade" "https://marmalade-repo.org/packages/"))

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   (quote
    ("e0c66085db350558f90f676e5a51c825cb1e0622020eeda6c573b07cb8d44be5" default)))
 '(package-selected-packages
   (quote
    (php-extras ede-php-autoload company-php ac-php php-mode neotree pdf-tools racket-mode omnisharp csharp-mode company))))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(package-initialize)

(set-frame-font "InputMono Medium" nil t)
(setq indent-tabs-mode nil)  ; set tabs to 4 spaces globally
(setq tab-width 4)
(setq company-idle-delay 0.01)  ; gotta go fast
(setq company-minimum-prefix-length 0)

(add-to-list 'load-path "~/.emacs.d/evil")
(require 'evil)

(evil-mode 1)  ; vim emulation
(electric-pair-mode 1)  ; insert two parens at a time
(show-paren-mode 1)  ; highlight matching parens
(global-linum-mode 1)  ; display line numbers
(load-theme 'xresources t)  ; generated by pywal

(add-to-list 'comint-output-filter-functions 'ansi-color-process-output)
(ansi-color-for-comint-mode-on)

(global-set-key [f12] 'ansi-term)
(global-set-key [f1] 'neotree-toggle)
(defalias 'yes-or-no-p 'y-or-n-p)  ; omgomg saves two keystrokes each time


;;; C#

(eval-after-load
  'company
  '(add-to-list 'company-backends #'company-omnisharp))

(defun csharp-mode-setup ()
  (omnisharp-mode)
  (company-mode-on)
  (flycheck-mode 1)
  (c-set-style "ellemtel")
  (setq indent-tabs-mode nil)
  (setq c-syntactic-indentation t)
  (setq c-basic-offset 4)
  (setq truncate-lines t)
  (setq tab-width 4)
  (setq evil-shift-width 4)
  (local-set-key (kbd "C-c r r") 'omnisharp-run-code-action-refactoring)
  (local-set-key (kbd "C-c C-c") 'recompile))

(add-hook 'csharp-mode-hook 'csharp-mode-setup t)


;;; Racket

(defun racket-mode-setup ()
  (setq tab-always-indent 'complete)
  (local-set-key [f5] racket-run))

(add-hook 'racket-mode-hook 'racket-mode-setup t)


;;; PHP

(defun php-mode-setup ()
  (require 'company-php)
  (require 'ede)
  (require 'ede-php-autoload-composer)
  (require 'ede-php-autoload/class-loader)
  (c-set-style "psr2")  ; php-enable... renders tab key useless
  (flycheck-mode 1)
  (company-mode t)
  (ac-php-core-eldoc-setup)
  (set (make-local-variable 'company-backends)
       '((php-extras-company company-dabbrev-code company-ac-php-backend) company-capf company-files))
  (ede-php-autoload-mode))  ; <3

(add-hook 'php-mode-hook 'php-mode-setup t)


;;; Emacs Lisp

(defun emacs-lisp-mode-setup ()
  (company-mode t))

(add-hook 'emacs-lisp-mode-hook 'emacs-lisp-mode-setup)
